
-- DATA EXPLORATION
-- Explore all objects in the database

select * from Information_schema.Tables

-- Explore all columns in the database

select * from Information_schema.columns 
where table_name ="dim_products"


-- DIMENSION EXPLORATION

-- Explore all countries our customers come from

Select distinct country from gold_dim_customers

-- Explore All categories " The major Divisions

Select distinct category, subcategory, product_name from gold.dim_products
order by 1,2,3

-- DATE EXPLORATION

-- Identify the earliest and latest date
-- How many years of sales are available

select 
order_date,
MIN(order_date) first_order_date,
Max(order_date) last_orderate,
datediff(year,MIN(order_date),Max(order_date)) order_range_months
from gold.fact_Sales

-- Find the youngest and oldest customers

select
 Min(birthdate) oldest_birthdate,
 datediff(year,Min(birthdate),Getdate()) as oldest_age,
Max(birthdate) youngest_birthdate,
datediff(year,Max(birthdate), getdate()) as youngest_date
from gold_dim_customers


-- MEASURE EXPLORATION

-- FIND the total sales

select 
sum(sales_amount) as total_Sales
from gold.fact_Sales

-- find the average. selling price
select
avg(sales_amount) as avg_sellingprice
from gold.fact_Sales

-- find how many items are sold
select 
sum(quantity) as totalitems_sold from gold.fact_sales

-- find the total number of orders
select
count(distinct order_number) as total_orders
from gold.fact_sales

-- find the total number of products

select count(distinct product_key) as total_products from gold.dim_products
-- find the total number of customers
select count(distinct customer_key) as total_customers from gold_dim_customers

-- find the total number of customers that has places an order

select count(distinct customer_key) as total_customers from gold.fact_Sales



-- Generate reoprt that shows all key metrices of the business


SELECT 'total sales' as measure_name, sum(sales_amount)as measure_value  from gold.fact_sales
Union all 
SELECT 'total quantity' as measure_name, sum(quantity)as measure_value  from gold.fact_sales
Union all
SELECT 'Average price' , avg(price) avg_price  from gold.fact_sales
Union all
SELECT 'total nr.products' , sum(sales_amount)  from gold.fact_sales
Union all
SELECT 'total nr.orders' , sum(sales_amount)  from gold.fact_sales
Union all
SELECT 'total no.customers', sum(sales_amount)  from gold.fact_sales


-- MAGNITUDE ANALYSIS

-- find total customers by countries
select country,
count(customer_key) as total_customers from gold.dim_customers 
group by country
order by total_customers desc
-- find total customers by genders
select gender,
count(customer_key) as total_customers from gold.dim_customers
group by gender
order by total_customers desc

-- find total products by category
select category,
count(product_key) as total_products from gold.dim_products
group by category
order by total_products desc

-- What is the average costs in each category?
select cost,
avg(cost) as avg_cost from gold.dim_products
 group by cost
 order by avg_cost desc

-- What is the total revenue generated for each category?
select 
p.category,
sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join
gold.dim_products p 
on p.product_key = f.product_key
group by category
order by total_revenue

-- Find the total revenue generated by each customer

select 
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by
c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc

-- What is the distribution of sold items across countries?

select
c.country,
sum(f.quantity) as sold_items
from gold.fact_sales f
left join
gold.dim_customers c
on c.customer_key = f.customer_key
group by 
c.country
order by sold_items desc

-- RANKING ANALYSIS

-- WHICH 5 products generate the highest revenue
select top 5
p.product_name,
sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
order by total_revenure desc


-- What are the 5 worst-performing products in terms of sales

select top 5
p.product_name,
sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
order by total_revenure 


-- WHICH 5 subcategory generate the highest revenue
select top 5
p.subcategory,
sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.subcategory
order by total_revenure desc


-- WHICH 5 subcategory generate the lowest revenue
select
* from (
select 
p.subcategory,
sum(f.sales_amount) total_revenue,
row_number() over(order by sum(f.sales_amount) desc) as rank_subcategory
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.subcategory)t
where rank_subcategory <=5


-- Find the top 10 customers who have generated the highest revenue 

select top 10
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold_dim_customers c
on c.customer_key = f.customer_key
group by
 c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc

-- Find 3 customers with the fewest orders placed

select top 3
c.customer_key,
c.first_name,
c.last_name,
count(distinct order_number) total_orders
from gold.fact_sales f
left join gold_dim_customers c
on c.customer_key = f.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_orders


